### ISSUE TITLE
Not able to load data with 2.0.0-next.1

### ISSUE THREAD

**Issue by knolljo** [pawcoding/astro-loader-pocketbase#17]
I'm using the 2.0.0-next version and trying to load some data from pb 0.23.5 with following setup:

```astro
// src/content/config.ts
import { defineCollection } from "astro:content";

import { pocketbaseLoader } from "astro-loader-pocketbase";
import {
  POCKETBASE_URL,
  POCKETBASE_USER,
  POCKETBASE_PASS,
} from "astro:env/server";

const data = defineCollection({
  loader: pocketbaseLoader({
    collectionName: "Data",
    url: POCKETBASE_URL,
    superuserCredentials: {
      email: POCKETBASE_USER,
      password: POCKETBASE_PASS,
    },
    updatedField: "updated",
  }),
});

export const collections = {
  data,
};
```
```astro
// src/pages/index.astro
---
import Layout from "../layouts/Layout.astro";

import { getCollection } from "astro:content";
const data = await getCollection("data");
console.table(data);
---

<Layout>
  {
    data.map((c) => (
      <p>
        {c.data.Name}: {c.data.Revenue}
      </p>
    ))
  }
</Layout>
```

The collection exists in pocketbase and has valid data, I'm also logged in as a superuser, because I can see that there is autocompletion for my collection.

When running `astro dev` the site works, but I following message in the console `The collection "data" does not exist or is empty. Ensure a collection directory with this name exists.`.

When running `astro sync` I get following error:

```sh
13:50:57 [pocketbase-loader] (Data) Fetching data as superuser
[InvalidContentEntryDataError] data → 2e3bgi43x91aruq data does not match collection schema.
collectionId: String must contain exactly 15 character(s)    
  Hint:
    See https://docs.astro.build/en/guides/content-collections/ for more information on content schemas.
  Error reference:
    https://docs.astro.build/en/reference/errors/invalid-content-entry-data-error/
  Location:
    C:\Users\knolljo\Git\website\node_modules\.pnpm\astro@5.0.4_jiti@1.21.6_rollup@4.28.1_typescript@5.7.2_yaml@2.6.1\node_modules\astro\dist\content\utils.js:158:26
  Stack trace:
    at getEntryDataAndImages (file:///C:/Users/knolljo/Git/website/node_modules/.pnpm/astro@5.0.4_jiti@1.21.6_rollup@4.28.1_typescript@5.7.2_yaml@2.6.1/node_modules/astro/dist/content/utils.js:158:26)
    at async parseData (file:///C:/Users/knolljo/Git/website/node_modules/.pnpm/astro@5.0.4_jiti@1.21.6_rollup@4.28.1_typescript@5.7.2_yaml@2.6.1/node_modules/astro/dist/content/content-layer.js:148:40)
    at async loadEntries (C:/Users/knolljo/Git/website/node_modules/.pnpm/astro-loader-pocketbase@2.0.0-next.1_astro@5.0.4_jiti@1.21.6_rollup@4.28.1_typescript@5.7.2_yaml@2.6.1_/node_modules/astro-loader-pocketbase/src/load-entries.ts:40:7)    
    at async Promise.all (index 0)
    at async file:///C:/Users/knolljo/Git/website/node_modules/.pnpm/p-queue@8.0.1/node_modules/p-queue/dist/index.js:187:36
```

Am I doing something wrong or might this be an error in the loader? Thanks in advance, I love pocketbase and astro!

**Comment by pawcoding** [comment]
Thanks for reporting this. I just realized that PocketBase 0.23 updated the way the collection id is generated when creating a collection. In previous versions it was something like `yw90zuwwv2y8kom` (string with 15 characters) while for new collections its now `pbc_4285667772` (string with 14 characters and special format).

I now updated the loader in [a1abf67](https://github.com/pawcoding/astro-loader-pocketbase/pull/16/commits/a1abf67be7989ec955126856f71961d4a7202e74) and removed the restriction for the collection id to be 15 characters long since this holds no additional type information anyways. Can you check if the new [`v2.0.0-next.3`](https://github.com/pawcoding/astro-loader-pocketbase/releases/tag/v2.0.0-next.3) release solves your issue?

**Comment by knolljo** [comment]
Can confirm, it works now. Thanks a lot!
