### ISSUE TITLE
Fetching Modified Data with an Invalid date

### ISSUE THREAD

**Issue by kmishmael** [pawcoding/astro-loader-pocketbase#18]
The issue is Modified data is not updated on server restart.

This stems from an invalid value `lastModified` passed to the fetch url query. `lastModified` is an ISO string which is in the format `2024-12-12T21:23:51.057Z`.

```ts
// Set the last modified date to the current date
context.meta.set("last-modified", new Date().toISOString()
```

However, Pocketbase uses the `RFC3399 format` which is in the format `2024-12-12 21:48:22.312Z` as noted [here](https://pocketbase.io/docs/collections/#datefield). Passing an ISO string to the query results in an empty result thus modified data is not updated.

A suggested fix would be to format the ISO time string to `RFC3399 format`:

```ts
context.meta.set("last-modified", new Date().toISOString().replace('T', ' '));
```

**Comment by pawcoding** [comment]
Should now be fixed in [v1.0.1](https://github.com/pawcoding/astro-loader-pocketbase/releases/tag/v1.0.1)
